export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CHANNELS = "GET_CHANNELS";
export const GET_CHANNEL = "GET_CHANNEL";
export const CHANNELS_LOADING = "CHANNELS_LOADING";
export const CLEAR_CHANNELS = "CLEAR_CHANNELS";
export const CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND";
